<?php

declare(strict_types=1);

namespace App\Tests\Integration\Infrastructure\Controller\Map;

use App\Tests\Integration\Infrastructure\Controller\AbstractWebTestCase;
use App\Tests\Mock\IgnGeocoderMockClient;

final class MapControllerTest extends AbstractWebTestCase
{
    public function testGet(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);
        $this->assertSecurityHeadersWithoutFraming();
        $this->assertMetaTitle('Carte - DiaLog', $crawler);

        // Search form is present
        $this->assertNotNull($crawler->selectButton('Rechercher'));
        $this->assertNotNull($crawler->filter('#search[name=search][autocomplete=off][spellcheck=false]')->first());

        // Filters form is open by default
        $this->assertStringContainsString('fr-collapse--expanded', $crawler->filter('#map-filters-accordion')->attr('class'));

        // The map exposes an MVT tiles URL template containing literal {z}/{x}/{y} placeholders.
        $tilesUrl = $crawler->filter('d-map')->attr('tilesurl');
        $this->assertNotNull($tilesUrl);
        $this->assertStringContainsString('{z}/{x}/{y}.mvt', $tilesUrl);

        // The form's action mirrors the same template so the client can substitute placeholders.
        $action = $crawler->filter('form')->attr('action');
        $this->assertNotNull($action);
        $this->assertStringContainsString('{z}/{x}/{y}.mvt', $action);

        // No initialBbox attribute when the user is anonymous and the cache table is empty.
        $this->assertNull($crawler->filter('d-map')->attr('initialbbox'));

        // The "Statut des arrêtés" filter (drafts) and the drafts endpoint are reserved to
        // logged-in users: neither the checkboxes nor the draftsUrl attribute are rendered.
        $this->assertCount(0, $crawler->filter('[name="map_filter_form[displayDrafts]"]'));
        $this->assertNull($crawler->filter('d-map')->attr('draftsurl'));
    }

    public function testGetRestoresFiltersFromQueryString(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?' . http_build_query([
            'map_filter_form' => [
                'displayTemporaryRegulations' => 'yes',
                'measureTypes' => ['speedLimitation'],
            ],
        ]));

        $this->assertResponseStatusCodeSame(200);

        $this->assertNull($crawler->filter('[name="map_filter_form[displayPermanentRegulations]"]')->attr('checked'));
        $this->assertSame('checked', $crawler->filter('[name="map_filter_form[displayTemporaryRegulations]"]')->attr('checked'));

        $this->assertSame('checked', $crawler->filter('[name="map_filter_form[measureTypes][]"][value="speedLimitation"]')->attr('checked'));
        $this->assertNull($crawler->filter('[name="map_filter_form[measureTypes][]"][value="noEntry"]')->attr('checked'));
    }

    public function testGetAuthenticatedRestoresPublishedWhenOpeningAnonymousLink(): void
    {
        // A link generated by an anonymous visitor carries filter params but never the
        // "Statut des arrêtés" marker. A logged-in user opening it must still see published
        // arrêtés: the "published" checkbox has to stay checked instead of being reset by the
        // absent checkbox.
        $client = $this->login();
        $crawler = $client->request('GET', '/carte?' . http_build_query([
            'map_filter_form' => [
                'displayPermanentRegulations' => 'yes',
                'displayTemporaryRegulations' => 'yes',
                'measureTypes' => ['noEntry'],
            ],
        ]));

        $this->assertResponseStatusCodeSame(200);

        $this->assertSame('checked', $crawler->filter('[name="map_filter_form[displayPublished]"]')->attr('checked'));
        $this->assertNull($crawler->filter('[name="map_filter_form[displayDrafts]"]')->attr('checked'));
    }

    public function testGetAuthenticatedKeepsPublishedUncheckedWhenExplicitlyUnset(): void
    {
        // When the status filter marker is present (link generated by a logged-in user) the
        // absent "published" checkbox is a deliberate choice and must be honoured.
        $client = $this->login();
        $crawler = $client->request('GET', '/carte?' . http_build_query([
            'map_filter_form' => [
                'measureTypes' => ['noEntry'],
                'displayDrafts' => 'yes',
                'statusFilterActive' => '1',
            ],
        ]));

        $this->assertResponseStatusCodeSame(200);

        $this->assertNull($crawler->filter('[name="map_filter_form[displayPublished]"]')->attr('checked'));
        $this->assertSame('checked', $crawler->filter('[name="map_filter_form[displayDrafts]"]')->attr('checked'));
    }

    public function testGetHasNoCsrfTokenLeakingIntoTheUrl(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);
        $this->assertCount(0, $crawler->filter('[name="map_filter_form[_token]"]'));
    }

    public function testGetAuthenticatedShowsStatusFilter(): void
    {
        $client = $this->login();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);

        // The "Statut des arrêtés" section exposes the published + drafts checkboxes...
        $this->assertCount(1, $crawler->filter('[name="map_filter_form[displayPublished]"]'));
        $this->assertCount(1, $crawler->filter('[name="map_filter_form[displayDrafts]"]'));

        // ...and the map element is given the authenticated drafts endpoint URL.
        $draftsUrl = $crawler->filter('d-map')->attr('draftsurl');
        $this->assertNotNull($draftsUrl);
        $this->assertStringContainsString('/carte/drafts.geojson', $draftsUrl);
    }

    public function testGetAuthenticatedExposesInitialBbox(): void
    {
        $client = $this->login();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);

        // department93User belongs to seineSaintDenisOrg, which has a geometry:
        // the initial bbox JSON is rendered into the d-map element.
        $initialBbox = $crawler->filter('d-map')->attr('initialbbox');
        $this->assertNotNull($initialBbox);
        $decoded = json_decode($initialBbox, true);
        $this->assertIsArray($decoded);
        $this->assertArrayHasKey('minLon', $decoded);
        $this->assertArrayHasKey('minLat', $decoded);
        $this->assertArrayHasKey('maxLon', $decoded);
        $this->assertArrayHasKey('maxLat', $decoded);
        $this->assertLessThan($decoded['maxLon'], $decoded['minLon']);
        $this->assertLessThan($decoded['maxLat'], $decoded['minLat']);
    }

    public function testShareButtonAndModalHiddenForAnonymousUser(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);
        $this->assertCount(0, $crawler->filter('d-map-share'));
    }

    public function testShareButtonAndModalVisibleForAuthenticatedUser(): void
    {
        $client = $this->login();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);

        $share = $crawler->filter('d-map-share');
        $this->assertCount(1, $share);

        // The organization select must contain the user's organizations.
        $options = $crawler->filter('#map-share-org-select option');
        $this->assertGreaterThan(0, $options->count());

        // The link/embed tabs are present.
        $this->assertCount(1, $crawler->filter('#map-share-tab-link'));
        $this->assertCount(1, $crawler->filter('#map-share-tab-embed'));
    }

    public function testGetWithOrganizationUuidUsesOrganizationBbox(): void
    {
        $client = static::createClient();
        // seineSaintDenisOrg has a geometry — use its UUID directly (no login needed).
        $crawler = $client->request('GET', '/carte?organizationUuid=8f9164ed-dc0f-4c98-ac18-2f590a1cfd22');

        $this->assertResponseStatusCodeSame(200);

        $initialBbox = $crawler->filter('d-map')->attr('initialbbox');
        $this->assertNotNull($initialBbox);
        $decoded = json_decode($initialBbox, true);
        // Seine-Saint-Denis bbox: lon ~[2.28, 2.60], lat ~[48.80, 49.01].
        $this->assertGreaterThan(2.0, $decoded['minLon']);
        $this->assertLessThan(3.0, $decoded['maxLon']);
        $this->assertGreaterThan(48.0, $decoded['minLat']);
        $this->assertLessThan(49.5, $decoded['maxLat']);
    }

    public function testGetWithUnknownOrganizationUuidReturnsNoBbox(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?organizationUuid=00000000-0000-0000-0000-000000000000');

        $this->assertResponseStatusCodeSame(200);
        $this->assertNull($crawler->filter('d-map')->attr('initialbbox'));
    }

    public function testGetWithRegulationOrderRecordUuidUsesRestrictionsBbox(): void
    {
        $client = static::createClient();
        // The "typical" regulation order record has geolocated restrictions in Paris
        // (lon ~2.34, lat ~48.90) — the map zooms onto their overall extent.
        $crawler = $client->request('GET', '/carte?regulationOrderRecordUuid=e413a47e-5928-4353-a8b2-8b7dda27f9a5');

        $this->assertResponseStatusCodeSame(200);

        $initialBbox = $crawler->filter('d-map')->attr('initialbbox');
        $this->assertNotNull($initialBbox);
        $decoded = json_decode($initialBbox, true);
        $this->assertLessThan($decoded['maxLon'], $decoded['minLon']);
        $this->assertLessThan($decoded['maxLat'], $decoded['minLat']);
        $this->assertGreaterThan(2.0, $decoded['minLon']);
        $this->assertLessThan(3.0, $decoded['maxLon']);
        $this->assertGreaterThan(48.0, $decoded['minLat']);
        $this->assertLessThan(49.5, $decoded['maxLat']);
    }

    public function testGetWithUnknownRegulationOrderRecordUuidReturnsNoBbox(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?regulationOrderRecordUuid=00000000-0000-0000-0000-000000000000');

        $this->assertResponseStatusCodeSame(200);
        $this->assertNull($crawler->filter('d-map')->attr('initialbbox'));
    }

    public function testGetWithDepartmentCodeFiltersAndZoomsOnDepartment(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?departmentCode=93&embed=1');

        $this->assertResponseStatusCodeSame(200);

        // La carte est centrée sur le contour du département.
        $decoded = json_decode($crawler->filter('d-map')->attr('initialbbox'), true);
        $this->assertEquals(['minLon' => 2.28, 'minLat' => 48.8, 'maxLon' => 2.6, 'maxLat' => 49.01], $decoded);

        // Le code est repris dans un champ caché du formulaire de filtres, donc dans l'URL des tuiles.
        $this->assertSame('93', $crawler->filter('d-map-form form input[type=hidden][name=departmentCode]')->attr('value'));

        // Le filtre n'apparaissant pas parmi les cases à cocher, la collectivité est indiquée.
        $boundaries = $crawler->filter('#map-administrative-boundaries');
        $this->assertStringContainsString('Carte limitée à', $boundaries->text());
        $this->assertSame('Seine-Saint-Denis', $boundaries->filter('.fr-tag')->text());
    }

    public function testGetWithSeveralAdministrativeBoundaryCodes(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?inseeCode=93070&epciCode=200054781&regionCode=11');

        $this->assertResponseStatusCodeSame(200);

        $form = $crawler->filter('d-map-form form');
        $this->assertSame('93070', $form->filter('input[type=hidden][name=inseeCode]')->attr('value'));
        $this->assertSame('200054781', $form->filter('input[type=hidden][name=epciCode]')->attr('value'));
        $this->assertSame('11', $form->filter('input[type=hidden][name=regionCode]')->attr('value'));

        $this->assertSame(
            ['Saint-Ouen-sur-Seine', 'Métropole du Grand Paris', 'Île-de-France'],
            $crawler->filter('#map-administrative-boundaries .fr-tag')->each(fn ($tag) => $tag->text()),
        );

        // La carte est centrée sur la première collectivité (la commune).
        $decoded = json_decode($crawler->filter('d-map')->attr('initialbbox'), true);
        $this->assertEquals(['minLon' => 2.31, 'minLat' => 48.89, 'maxLon' => 2.36, 'maxLat' => 48.92], $decoded);
    }

    public function testGetWithAdministrativeBoundaryCodeTakesPrecedenceOverOrganizationUuid(): void
    {
        $client = static::createClient();
        // seineSaintDenisOrg, mais la carte est limitée aux Ardennes.
        $crawler = $client->request('GET', '/carte?organizationUuid=8f9164ed-dc0f-4c98-ac18-2f590a1cfd22&departmentCode=08');

        $this->assertResponseStatusCodeSame(200);

        $decoded = json_decode($crawler->filter('d-map')->attr('initialbbox'), true);
        $this->assertEquals(['minLon' => 4.0, 'minLat' => 49.2, 'maxLon' => 5.4, 'maxLat' => 50.2], $decoded);
    }

    /**
     * @dataProvider provideUnusableAdministrativeBoundaryCodes
     */
    public function testGetIgnoresUnusableAdministrativeBoundaryCode(string $query): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?' . $query);

        // La carte s'affiche sans filtre plutôt que de renvoyer une erreur.
        $this->assertResponseStatusCodeSame(200);
        $this->assertCount(0, $crawler->filter('#map-administrative-boundaries'));
        $this->assertCount(0, $crawler->filter('d-map-form form input[type=hidden][name=departmentCode]'));
        $this->assertNull($crawler->filter('d-map')->attr('initialbbox'));
    }

    public function provideUnusableAdministrativeBoundaryCodes(): array
    {
        return [
            'code inconnu du COG' => ['departmentCode=99'],
            'code mal formé' => ['departmentCode=abc'],
            'code vide' => ['departmentCode='],
            'source des contours indisponible' => ['departmentCode=' . IgnGeocoderMockClient::UNAVAILABLE_DEPARTMENT_CODE],
        ];
    }

    public function testGetWithoutAdministrativeBoundaryCodeHasNoBoundaryFilter(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);
        $this->assertCount(0, $crawler->filter('#map-administrative-boundaries'));
        $this->assertCount(0, $crawler->filter('d-map-form form input[type=hidden]:not([name^="map_filter_form"])'));
    }

    public function testShareModalExposesOrganizationAdministrativeBoundaryCode(): void
    {
        $client = $this->login();
        $crawler = $client->request('GET', '/carte');

        $this->assertResponseStatusCodeSame(200);

        // department93User appartient à seineSaintDenisOrg (département 93) : le code d'intégration
        // de l'iframe limitera la carte à ce département.
        $option = $crawler->filter('#map-share-org-select option[value="8f9164ed-dc0f-4c98-ac18-2f590a1cfd22"]');
        $this->assertSame('departmentCode', $option->attr('data-boundary-parameter'));
        $this->assertSame('93', $option->attr('data-boundary-code'));

        // ...et à dialogOrg, qui n'a pas de code : pas de filtre par collectivité.
        $option = $crawler->filter('#map-share-org-select option[value="e0d93630-acf7-4722-81e8-ff7d5fa64b66"]');
        $this->assertCount(1, $option);
        $this->assertNull($option->attr('data-boundary-parameter'));
        $this->assertNull($option->attr('data-boundary-code'));
    }

    public function testGetEmbedHidesHeaderAndFooter(): void
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/carte?embed=1');

        $this->assertResponseStatusCodeSame(200);
        // Embed mode: neither the global header nor the footer are rendered.
        $this->assertCount(0, $crawler->filter('header.fr-header'));
        $this->assertCount(0, $crawler->filter('footer'));
        // The map itself is still rendered.
        $this->assertCount(1, $crawler->filter('d-map'));
        // The "share" button is also hidden inside the iframe.
        $this->assertCount(0, $crawler->filter('d-map-share'));
    }
}
