services:
    outscale_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            -  endpoint: '%env(S3_ENDPOINT)%'
               accessKeyId: '%env(S3_ACCESS_KEY)%'
               accessKeySecret: '%env(S3_SECRET_KEY)%'

flysystem:
    storages:
        cdn.storage:
            adapter: 'asyncaws'
            options:
                client: 'outscale_client'
                bucket: '%env(S3_BUCKET)%'
        memory.storage:
            adapter: 'memory'
        local.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/storage'
        storage:
            adapter: 'lazy'
            options:
                source: '%env(APP_STORAGE_SOURCE)%'
