framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - validation
                    - doctrine_transaction
            messenger.bus.queries:
                middleware:
                    - validation

        transports:
            amqp:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                amqp: 'in-memory://'
