monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - eudonet_paris_import
        - bac_idf_import

    handlers:
        eudonet_paris_import:
            level: debug
            type: rotating_file
            path: "%kernel.project_dir%/log/eudonet_paris/import.%kernel.environment%.log"
            formatter: monolog.formatter.json
            channels: ["eudonet_paris_import"]
        bac_idf_import:
            level: debug
            type: rotating_file
            path: "%kernel.project_dir%/log/bac_idf/import.%kernel.environment%.log"
            formatter: monolog.formatter.json
            channels: ["bac_idf_import"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
