twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['common/form/dsfr_theme.html.twig']

when@test:
    twig:
        strict_variables: true

when@prod:
    twig:
        globals:
            matomo:
                url: https://stats.data.gouv.fr/
                site_id: 288
