#!/usr/bin/env python3
"""
Turn French city JSON data obtained from https://github.com/etalab/decoupage-administratif
into an SQL file for quick and efficient import.
"""
import argparse
import json
from pathlib import Path
import textwrap

TABLE_NAME = "fr_city"

SQL_TEMPLATE = textwrap.dedent(
    """\
    DELETE FROM fr_city;

    INSERT INTO fr_city (insee_code, name, departement)
    VALUES
    {values};
    """
)


def main(input_path: Path, output_path: Path):
    rows = json.loads(input_path.read_text())

    values_list = []

    for row in rows:
        if row["type"] in ("commune-deleguee", "commune-associee"):
            continue

        insee_code = row["code"]
        name = row["nom"].replace("'", "\\'")
        departement = row["departement"]
        values_list.append(f"('{insee_code}', E'{name}', '{departement}')")

    sql = SQL_TEMPLATE.format(values=",\n".join(values_list))

    output_path.write_text(sql)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("input_path", type=Path)
    parser.add_argument("output_path", type=Path)
    args = parser.parse_args()

    main(args.input_path, args.output_path)
